ODBC_SUCCESS, ODBC_ERROR, ODBC_INSERT,ODBC_INSERT_SETRANGE,ODBC_SQL = 0,1,2,3,4
SILICAN_CONNECTED,SILICAN_ERROR,SILICAN_CONNECTION,SILICAN_USER_FOUND,SILICAN_RELEASE,SILICAN_SQL,SILICAN_SETRANGE,SILICAN_PROGRESS,SILICAN_HISTORY_SQL,SILICAN_SUCCESS,VOIP_SQL = 0,1,2,3,4,5,6,7,8,9,10
VOIP_NEW,VOIP_ANSWERED = 1,2
